var sequences = [
  {
    name: 'Homo sapieni (human) histone H2A gene',
    sequence: 'atgtctggacgagggaagcagggaggaaaagcacgcgccaagtctaagtctcgctcttctagagcgggtttgcagtttcccgtaggccggatccatcgtctgcttcgtaagggaaactatgcagagcggataggggcaggcgcaccagtgtatttggcggcagtgttagagtatctcacagcagaaatccttgagctggcaggcaatgcgtctcgcgataacaaaaaaactcgcattattccccgccacctgcagctagcgatccgcaatgatgaggaactcaataagcttttgggcggcgtgaccattgcccagggcggagtcctgcctaacattcaggcagtgctgctgcccaagaagactgagagtcaccaccataaagcccaaagcaagtaa',
  },
  {
    name: 'Pan troglodytes (chimpanzee) histone H2A gene',
    sequence: 'atgtctggacgagggaagcagggaggaaaagcacgcgccaagtctaagtctcgctcttctagagcgggtttgcagtttcccgtaggccggatccatcgtctgcttcgtaagggaaactatgcagagcggataggggcaggcgcaccagtgtatttggcggcagtgttagagtatctcacagcagaaatccttgagctggcaggcaatgcgtctcgcgataacaaaaaaactcgcattattccccgccacctgcagctagcgatccgcaatgatgaggaactcaataagcttttgggcggcgtgaccattgcccagggcggagtcctgcctaacattcaggcagtgctgctgcccaagaagactgagagtcaccaccataaagcccaaagcaagtaa',
  },
  {
    name: 'Canis familiaris (dog) histone H2A gene',
    sequence: 'atgtctggccgaggcaagcagggcggcaaggcgcgcgccaaggccaagtcccgctcgtcccgggcggggctgcagttcccggtgggtcgcgtgcaccgtctcctccgcaagggcaactactcggagcgggtcggggcgggcgcgccggtgtacctggcggccgtgctggagtacctgacggccgagatcctggagctggcgggcaacgcggcccgcgacaacaagaagacgcgcatcatcccgcgccacctgcagctggccatccgcaacgacgaggagctcaacaagctgctgggccgcgtgaccatcgcgcagggcggcgtcctgcccaacatccaggccgtgctgctgcccaagaagaccgagagccaccacaaggccaagagcaagtga',
  },
  {
    name: 'Heliconius melpomene (postman butterfly) histone H2A gene',
    sequence: 'atggctggtggtaaagcgggcaaagattctggcaaagccaaggcgaaagctgtctcacgatcggctcgggcgggcttgcagttccctgtgggtagaattcatagacatctcaaaaataggactacgagtcacggccgtgtcggcgcaacggctgccgtttattctgcggctattcttgaatatctcacagccgaggttttagagttagcgggcaatgcatccaaagatcttaaagtaaaacgtatcactcccagacatttacaactagctatcagaggagacgaggagctggacagcttgatcaaagccaccattgcgggaggtggtgtcatcccacatattcacaaatcactcatcggtaaaaaaggaggaccaggggcacctgtttaa',
  },
  {
    name: 'Saccharomyces mikatae (yeast) histone H2A gene',
    sequence: 'atgtcaggaaaagctcatggaggtaaaggtaaatcaggcgctaaagatggcggttcattgagatctcagtcctcctcggcaagggctgggttgcagtttccagtcggtagaattaagcgttacctaaaaaggcatgctactggccgaacaagagtaggatccaaagctgccatttatttgactgcggtgttagaatatttgactgctgaagtgctggagttggccggtaatgcagctaaggatcttaaagtcaaaagaatcaccccaagacatttgcaattggccattaggggtgacgatgaattagattctttgatcagagctacgattgcttcaggtggtgttttgcctcatataaataaggcgttactattaaaagtggaaaaaaagggcaataagaaatga',
  },
  {
    name: 'Phanerochaete chrysosporium (fungus) histone H2A gene',
    sequence: 'atgtcgcagaggacgctgcagactaggagtcagcgcgcaggcttgcagttccccgtcggccgtatccaccgttacctcaagcagaagacacagcacaacgtgcgcataggcgcaaaggctgcagtctacacctctgctatcctggagtacctcaccgctgaagtactcgagctcgctggtaatgcgtcaaaggacttgcgagtcaagcgcataacaccacgccacctgcagctggctattcgcggcgacgaggaactcgacacacttgttcgggcaactatcgcgggtggaggtgtcctcccattcatccacaagagtctcacaaacccaaagggcaagaaggcgacagaacagccttcataa',
  },
];

export default sequences;
