// temp frontend storage until backend database is implemented
const sequences = {
  'H2A genes': [
    [
      'Homo sapieni (human) histone H2A gene',
      'atgtctggacgagggaagcagggaggaaaagcacgcgccaagtctaagtctcgctcttctagagcgggtttgcagtttcccgtaggccggatccatcgtctgcttcgtaagggaaactatgcagagcggataggggcaggcgcaccagtgtatttggcggcagtgttagagtatctcacagcagaaatccttgagctggcaggcaatgcgtctcgcgataacaaaaaaactcgcattattccccgccacctgcagctagcgatccgcaatgatgaggaactcaataagcttttgggcggcgtgaccattgcccagggcggagtcctgcctaacattcaggcagtgctgctgcccaagaagactgagagtcaccaccataaagcccaaagcaagtaa',
    ],
    [
      'Pan troglodytes (chimpanzee) histone H2A gene',
      'atgtctggacgagggaagcagggaggaaaagcacgcgccaagtctaagtctcgctcttctagagcgggtttgcagtttcccgtaggccggatccatcgtctgcttcgtaagggaaactatgcagagcggataggggcaggcgcaccagtgtatttggcggcagtgttagagtatctcacagcagaaatccttgagctggcaggcaatgcgtctcgcgataacaaaaaaactcgcattattccccgccacctgcagctagcgatccgcaatgatgaggaactcaataagcttttgggcggcgtgaccattgcccagggcggagtcctgcctaacattcaggcagtgctgctgcccaagaagactgagagtcaccaccataaagcccaaagcaagtaa',
    ],
    [
      'Canis familiaris (dog) histone H2A gene',
      'atgtctggccgaggcaagcagggcggcaaggcgcgcgccaaggccaagtcccgctcgtcccgggcggggctgcagttcccggtgggtcgcgtgcaccgtctcctccgcaagggcaactactcggagcgggtcggggcgggcgcgccggtgtacctggcggccgtgctggagtacctgacggccgagatcctggagctggcgggcaacgcggcccgcgacaacaagaagacgcgcatcatcccgcgccacctgcagctggccatccgcaacgacgaggagctcaacaagctgctgggccgcgtgaccatcgcgcagggcggcgtcctgcccaacatccaggccgtgctgctgcccaagaagaccgagagccaccacaaggccaagagcaagtga',
    ],
    [
      'Heliconius melpomene (postman butterfly) histone H2A gene',
      'atggctggtggtaaagcgggcaaagattctggcaaagccaaggcgaaagctgtctcacgatcggctcgggcgggcttgcagttccctgtgggtagaattcatagacatctcaaaaataggactacgagtcacggccgtgtcggcgcaacggctgccgtttattctgcggctattcttgaatatctcacagccgaggttttagagttagcgggcaatgcatccaaagatcttaaagtaaaacgtatcactcccagacatttacaactagctatcagaggagacgaggagctggacagcttgatcaaagccaccattgcgggaggtggtgtcatcccacatattcacaaatcactcatcggtaaaaaaggaggaccaggggcacctgtttaa',
    ],
    [
      'Saccharomyces mikatae (yeast) histone H2A gene',
      'atgtcaggaaaagctcatggaggtaaaggtaaatcaggcgctaaagatggcggttcattgagatctcagtcctcctcggcaagggctgggttgcagtttccagtcggtagaattaagcgttacctaaaaaggcatgctactggccgaacaagagtaggatccaaagctgccatttatttgactgcggtgttagaatatttgactgctgaagtgctggagttggccggtaatgcagctaaggatcttaaagtcaaaagaatcaccccaagacatttgcaattggccattaggggtgacgatgaattagattctttgatcagagctacgattgcttcaggtggtgttttgcctcatataaataaggcgttactattaaaagtggaaaaaaagggcaataagaaatga',
    ],
    [
      'Phanerochaete chrysosporium (fungus) histone H2A gene',
      'atgtcgcagaggacgctgcagactaggagtcagcgcgcaggcttgcagttccccgtcggccgtatccaccgttacctcaagcagaagacacagcacaacgtgcgcataggcgcaaaggctgcagtctacacctctgctatcctggagtacctcaccgctgaagtactcgagctcgctggtaatgcgtcaaaggacttgcgagtcaagcgcataacaccacgccacctgcagctggctattcgcggcgacgaggaactcgacacacttgttcgggcaactatcgcgggtggaggtgtcctcccattcatccacaagagtctcacaaacccaaagggcaagaaggcgacagaacagccttcataa',
    ],
  ],
};

export default sequences;
